### ISSUE TITLE
Add duplicates to missing report

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/earthcube_utilities#119]
Originally, a separate cli call, and is a command that might be used across sources to identify duplicate url's and she's 

Do we add the duplicate urls to the missing report...
we grab the list to identify the URL that are not loaded, extras that are loaded, why not just add a section for duplicates.

duplicate_count: count
duplicates: [
 { url: url, [{sha, identifiertype, lastmodified},...] },
{ url: url, [{sha, identifiertype, lastmodified},...] },
]

**Comment by ylyangtw** [comment]
@valentinedwv Since it's duplicates, maybe should not be in missing_reports?
We can either have a separate duplicate report or merge duplicates and missing reports to one report

**Comment by valentinedwv** [comment]
Name change is fine... 
'load_report_s3'  
'load_report_full' or 'load_report_graph'

**Comment by ylyangtw** [comment]
Reource loading report

**Comment by valentinedwv** [comment]
close. there is a  "extra_in_summon"
