### ISSUE TITLE
Summary: Keyword rendering as NaN.

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/earthcube_utilities#138]
<img width="1150" alt="Screen Shot 2023-11-15 at 2 23 14 PM" src="https://github.com/earthcube/earthcube_utilities/assets/851784/84041fbb-e8f8-4f0a-bde9-615cab4cc0d1">

Is this a reading from the release file issue?

**Comment by ylyangtw** [comment]
@valentinedwv which instance is this? aws?

**Comment by valentinedwv** [comment]
See #147 and the about config on earthcube.netlify.app

**Comment by ylyangtw** [comment]
close this as it's fixed


![Image](https://github.com/earthcube/earthcube_utilities/assets/63822845/765f17b6-d56d-44a6-8524-d26ce8d1f20e)
