### ISSUE TITLE
Notebook proxy changes

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/earthcube_utilities#16]
I set most of them to the new mknb2.py flask routes I'm trying for now; eg. [txt_query](https://utils.geocodes.ncsa.illinois.edu/txt_query_csv/?q=norway) and [get_graph](https://geocodes.ncsa.illinois.edu/get_graph_csv/?g=urn:gleaner:summoned:iedadata:37dc4a143fb034cdf978c76077cccb9728d55294)
to keep them alive; but will transfer to the other services soon; maybe put above under [utils](https://utils.geocodes.ncsa.illinois.edu/alive). ..
added [beta](https://beta.geocodes.ncsa.illinois.edu/). .. to redir to prod for now; will add my dev version soon
[graph](https://graph.geocodes.ncsa.illinois.edu/) does have blaze on it; we have to start filling the other repos soon; as ppl asked at agu

**Comment by valentinedwv** [comment]
These routines can be added to the existing codebase in this repo on a branch.
 A container should be built , you may need to add a branch to the workflow, then pull and test using postman.

**Comment by valentinedwv** [comment]
Added an example of a cleaner reimplemation of what is on mbcode/ec
at present, it just mocks one, example. Clean reimplemation is needed for the utility that does the jsonld output.
https://github.com/earthcube/earthcube_utilities/blob/0ddbc9b325aa60876f347bd2a83dbc945cd1de97/notebook_proxy/mknb.py#L618

**Comment by valentinedwv** [comment]
Created clean RDF code...
https://github.com/earthcube/earthcube_utilities/blob/68e458a694b16ea667d775f9a289c3bb103e8e6d/earthcube_utilities/ec/sos_json/rdf.py#L76

We can't do framed reliably since we need to know what object we want... which is the schemaType, but is not yet knows how to do the request in the interface.
just use form="compact".

**Comment by valentinedwv** [comment]
jsonld from graph complete.

**Comment by MBcode** [comment]
For the notebooks, I started to skip these new routes, because the notebook can already just run that python code anyway; the new routes were more to make it easier for the js-front-end to get the RDF in whatever format it wanted; btw, the front end should probably use an RDF lib vs minipulating the jsonld as json, bc it would probably be easier looking at them as triples
