### ISSUE TITLE
summary keywords break into separates

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/earthcube_utilities#183]
JSONLD from [pangeo](https://github.com/earthcube/GeoCODES-Metadata/blob/main/metadata/Dataset/actualdata/pangeo_keywords.json) using [semi-colons in the kwords](https://github.com/earthcube/GeoCODES-Metadata/blob/fe390c435501c6409b399dcbc26826ac6a54dc48/metadata/Dataset/actualdata/pangeo_keywords.json#L1821)
`"keywords": "Carbon; CO2; Lithology; nutrients; river; water chemistry; Weathering"`
https://github.com/earthcube/GeoCODES-Metadata/blob/fe390c435501c6409b399dcbc26826ac6a54dc48/metadata/Dataset/actualdata/pangeo_keywords.json#L1821

Summarize needs to split these into individual keywords

**Comment by valentinedwv** [comment]
converted semicolons into commas
that should work with facetsearch

**Comment by ylyangtw** [comment]
closed as it's done
