### ISSUE TITLE
handling distribution/encodingFormat arrays

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcube/earthcube_utilities#2]
looking at https://geocodes.earthcube.org/#/dataset/urn:gleaner:milled:magic:25cfe78f54d1152dcae8439cf2c26a9b319a48f3
the distribution is:

```
"https://schema.org/distribution": 
{ "@type": 
"https://schema.org/DataDownoad" ,
"https://schema.org/contentUrl": 
"https://earthref.org/MagIC/download/8470/magic_contribution_847015032.txt" ,
"https://schema.org/encodingFormat": 
           [ "text/plain; application=magic-tsv" , "MagIC-tsv-Multipart"  ]  } ,
```
The encodingFormat Value is an array. When passed to the processing notebook using the 'open in CoLAB' link from the dataset landing page, this gets passed as
 `ext = "text/plain__application=magic-tsv___MagIC-tsv-Multipart"`

this would be hard (Impossible?) to parse.  Can we pass this as a JSON array-- duplicate what is in the schema:encodingFormat value, or at least have a consistent pattern for mapping spaces, semi-colons, commas to distinct characters (could just omit spaces)?   See related issue on encoding format vs. file extension...

**Comment by valentinedwv** [comment]
mknb redirect to collab needs to utilize uri encoding, plus a hash correction.

http://141.142.218.86:3031/mknb?url=https://earthref.org/MagIC/download/8470/magic_contribution_847015032.txt&ext=text%2Fplain%3B%20application%3Dmagic-tsv%20%3B%20MagIC-tsv-Multipart&urn=urn:gleaner:milled:magic:25cfe78f54d1152dcae8439cf2c26a9b319a48f3&encoding=text%2Fplain%3B%20application%3Dmagic-tsv%20%3B%20MagIC-tsv-Multipart&

Javascript... 
```javascript
    encoding = encoding.replace('#',"<hash>")
      encoding = encodeURIComponent(encoding)

      contentUrl = contentUrl.replace('#',"<hash>")
```

python might been a join to merge array into a list for url passing.

**Comment by MBcode** [comment]
let us know if still an issue, but looks like it was handled
