### ISSUE TITLE
Modularize the scripts under earthcube_utilities

### ISSUE THREAD

**Issue by ylyangtw** [earthcube/earthcube_utilities#69]
There are more and more scripts under earthcube_utilities/ec and some of the codes have been used repeatedly, like input parameters, read glean file, etc.
Start a script for general codes and make them modularized and reusable by other scripts.

**Comment by valentinedwv** [comment]
Good idea on the standard parameters, but I was thinking more like the logic in the identifiers script be moved into a module/method.

Think that scripts like the three summarize might be merged into one or two scripts.

Or the pattern could be more like a `cmd tool action [options] arg [..args]` 
like is done in gleaner console (glcon)

**Comment by ylyangtw** [comment]
Python click may be a good tool
https://click.palletsprojects.com/en/8.1.x/

**Comment by ylyangtw** [comment]
This PR tested each function, added docs and unit tests, and cleaned some comments.
https://github.com/earthcube/earthcube_utilities/pull/91
