### ISSUE TITLE
Speed up ldentifier summary by using a dataframe

### ISSUE THREAD

**Issue by ylyangtw** [earthcube/earthcube_utilities#70]
[earthcube_utilities/src/ec/summarize_identifier_metadata.py](https://github.com/earthcube/earthcube_utilities/pull/64/files/76322e4a7d01d22ea3ad46aaeab6d33a9b9d5fd7#diff-1aa8d805e296e599562b3b6cb376754fda32b4086be2117a668e760bf02fdbde)
Speed this up by loading jsonld's into a dataframe, and using pandarallel to parallelize

ref:
[earthcube_utilities/earthcube_utilities/src/ec/sitemap/sitemap.py](https://github.com/earthcube/earthcube_utilities/blob/eeabc6c5d7a7c532011de70824e76a914b607d43/earthcube_utilities/src/ec/sitemap/sitemap.py#L88)

**Comment by valentinedwv** [comment]
Do not  think we need this. works fine
