### ISSUE TITLE
HTML Rendering of stats and information from reports

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/earthcube_utilities#83]
Several types of summaries needed: (might split into separate issues)
1)  **[about page](https://github.com/earthcube/facetsearch/issues/109).**
   * this needs to be rendered using information from the sources spreadsheet (has the description; not yet in a gleanerio config). 
   *  a manual (weekly task) would build a quick summary of the sources loaded into the a community graph, and in put it in an s3 bucket. 
        * basically, a community/tenant would show  sources in it's graph, and the Geocodes would show all loaded sources.  
   *  The (JSON?) file pushed to the s3 repo may have more than just the graph summary from the spaql query, it might have the descriptions, logos, and other information pulled from the 'sources' googlesheet.

2) **Graph report for each source**
   * This page should be able to read the reports/latest/{source} s3 bucket/path, and render an HTML file of the results. 

 _Section: Missing report details._ 
html render of details. Might need an overflow for the missing summon url's etc

_Section: Identifier Report_
Summary of what identifiers were used.

_Section graph report:_
HTML render of the graph report. Might start with a few of the properties for now. 

_(future)  Section: data issue assistance_
Create a section that has links so that we/others can more easily QA the issues
the sha to original url mapping is in the bucket_urls.csv... this might be used to add links to the original soruces in the missing url's/gaphs listings. 

|| missing summon || schema.org validator || original source link ||

|| missing graph sha ||  link to s3 file || schema.org validator || original source link ||

3) **detailed shcal validation report.**
Pagemill rendering of validation report.
    *

**Comment by valentinedwv** [comment]
Sparkline example from @MBcode https://github.com/earthcube/ec/blob/master/test/crawl/localConfig4Counts.py
info is available in the missing reports json files for each source

**Comment by ylyangtw** [comment]
the about page should include reports and org from minio
